### ISSUE TITLE
Couple of papers you might be interested in

### ISSUE THREAD

**Issue by arrivets** [DavidWalley/ByzAffirm#1]
Great project!

Here are two articles you might want to include in you research reading list:
-  This one talks about Full Information Protocols, where peers tell each other everything they know at 
  each step. Also defines a formalism to extract common knowledge from that data. It talks about a 
  Communication Graph rather than a Hashgraph.
[A Characterization of Eventual Byzantine Agreement. Halpern, Moses, and Waarts]( https://epubs.siam.org/doi/pdf/10.1137/S0097539798340217)

-  This one is the Bible.
[Time, Clocks, and the Ordering of Events in a Distributed System. Lamport](https://lamport.azurewebsites.net/pubs/time-clocks.pdf)

You might also be interested in this [article](https://medium.com/monet-network/from-peanuts-to-hashgraph-46c2308982c5) I wrote about the patents, and our implementation of a hashgraph-inspired consensus system,[ Babble](https://github.com/mosaicnetworks/babble)

**Comment by DavidWalley** [comment]
Thanks Martin,I am reading through the articles you sent, and will have to get a bit further to know if they are relevant. I have included two of your links on my page because I like a bit of humor, and because it is good to know the state of the art in 1978.Keep in touch - I am starting to get a nice little group of high quality people together, and will include you in our discussions if you are interested.Dave


-------- Original Message --------
Subject: [DavidWalley/ByzAffirm] Couple of papers you might be
interested in (#1)

**Comment by arrivets** [comment]
Thanks David. Would love to be in your mailing list.
I ll close the issue then.
